Name: Khursheed Ahmed
ID: F2022065038

In [1]:
!pip3 install pandas

WARNING: The directory '/Users/macbook/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: pandas in /Users/macbook/Desktop/NLP/myenv/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/macbook/Desktop/NLP/myenv/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/macbook/Desktop/NLP/myenv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/macbook/Desktop/NLP/myenv/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/macbook/Desktop/NLP/myenv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Users/macbook/Desktop/NLP/myenv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/macbook/Desktop/Machine Learning/pandas/dataset/diabetes.csv")

In [4]:
df.head()

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Outcome.1
0,0.0,6,148,72,35,0,33.6,0.627,50,1,1.0
1,1.0,1,85,66,29,0,26.6,0.351,31,0,-1.0
2,2.0,8,183,64,0,0,23.3,0.672,32,1,1.0
3,3.0,1,89,66,23,94,28.1,0.167,21,0,-1.0
4,4.0,0,137,40,35,168,43.1,2.288,33,1,1.0

In [5]:
df.tail()

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Outcome.1
763,NaN,10,101,76,48,180,32.9,0.171,63,0,NaN
764,NaN,2,122,70,27,0,36.8,0.340,27,0,NaN
765,NaN,5,121,72,23,112,26.2,0.245,30,0,NaN
766,NaN,1,126,60,0,0,30.1,0.349,47,1,NaN
767,NaN,1,93,70,31,0,30.4,0.315,23,0,NaN

In [6]:
!ls

Diabetes.ipynb  PandasLab.ipynb dataset

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Index                     10 non-null     float64
 1   Pregnancies               768 non-null    int64
 2   Glucose                   768 non-null    int64
 3   BloodPressure             768 non-null    int64
 4   SkinThickness             768 non-null    int64
 5   Insulin                   768 non-null    int64
 6   BMI                       768 non-null    float64
 7   DiabetesPedigreeFunction  768 non-null    float64
 8   Age                       768 non-null    int64
 9   Outcome                   768 non-null    int64
 10  Outcome.1                 27 non-null     float64
dtypes: float64(4), int64(7)
memory usage: 66.1 KB

In [8]:
df.isnull().sum()

Index                       758
Pregnancies                   0
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                       0
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
Outcome.1                   741
dtype: int64

In [9]:
df.count()

Index                        10
Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
Outcome.1                    27
dtype: int64

In [10]:
df.mean()

Index                         4.500000
Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
Outcome.1                     0.333333
dtype: float64

In [11]:
df.std()

Index                         3.027650
Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
Outcome                       0.476951
Outcome.1                     0.960769
dtype: float64

In [12]:
df.min()

Index                        0.000
Pregnancies                  0.000
Glucose                      0.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                          0.000
DiabetesPedigreeFunction     0.078
Age                         21.000
Outcome                      0.000
Outcome.1                   -1.000
dtype: float64

In [13]:
df.max()

Index                         9.00
Pregnancies                  17.00
Glucose                     199.00
BloodPressure               122.00
SkinThickness                99.00
Insulin                     846.00
BMI                          67.10
DiabetesPedigreeFunction      2.42
Age                          81.00
Outcome                       1.00
Outcome.1                     1.00
dtype: float64

In [14]:
df.describe()

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Outcome.1
count,10.00000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,27.000000
mean,4.50000,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958,0.333333
std,3.02765,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951,0.960769
min,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000,-1.000000
25%,2.25000,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000,-1.000000
50%,4.50000,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000,1.000000
75%,6.75000,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000,1.000000
max,9.00000,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000,1.000000

In [15]:
df.drop(index = 0, axis= 0)

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Outcome.1
1,1.0,1,85,66,29,0,26.6,0.351,31,0,-1.0
2,2.0,8,183,64,0,0,23.3,0.672,32,1,1.0
3,3.0,1,89,66,23,94,28.1,0.167,21,0,-1.0
4,4.0,0,137,40,35,168,43.1,2.288,33,1,1.0
5,5.0,5,116,74,0,0,25.6,0.201,30,0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...
763,NaN,10,101,76,48,180,32.9,0.171,63,0,NaN
764,NaN,2,122,70,27,0,36.8,0.340,27,0,NaN
765,NaN,5,121,72,23,112,26.2,0.245,30,0,NaN
766,NaN,1,126,60,0,0,30.1,0.349,47,1,NaN
767,NaN,1,93,70,31,0,30.4,0.315,23,0,NaN

In [17]:
df.drop(columns = 'Pregnancies', axis= 1)

,Index,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Outcome.1
0,0.0,148,72,35,0,33.6,0.627,50,1,1.0
1,1.0,85,66,29,0,26.6,0.351,31,0,-1.0
2,2.0,183,64,0,0,23.3,0.672,32,1,1.0
3,3.0,89,66,23,94,28.1,0.167,21,0,-1.0
4,4.0,137,40,35,168,43.1,2.288,33,1,1.0
...,...,...,...,...,...,...,...,...,...,...
763,NaN,101,76,48,180,32.9,0.171,63,0,NaN
764,NaN,122,70,27,0,36.8,0.340,27,0,NaN
765,NaN,121,72,23,112,26.2,0.245,30,0,NaN
766,NaN,126,60,0,0,30.1,0.349,47,1,NaN
767,NaN,93,70,31,0,30.4,0.315,23,0,NaN

In [18]:
df.iloc[2]

Index                         2.000
Pregnancies                   8.000
Glucose                     183.000
BloodPressure                64.000
SkinThickness                 0.000
Insulin                       0.000
BMI                          23.300
DiabetesPedigreeFunction      0.672
Age                          32.000
Outcome                       1.000
Outcome.1                     1.000
Name: 2, dtype: float64

In [19]:
df.iloc[:,-1]

0      1.0
1     -1.0
2      1.0
3     -1.0
4      1.0
      ...
763    NaN
764    NaN
765    NaN
766    NaN
767    NaN
Name: Outcome.1, Length: 768, dtype: float64

In [20]:
df.iloc[:,-2]

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [21]:
df.iloc[:,0]

0      0.0
1      1.0
2      2.0
3      3.0
4      4.0
      ...
763    NaN
764    NaN
765    NaN
766    NaN
767    NaN
Name: Index, Length: 768, dtype: float64

In [22]:
df.iloc[:,1]

0       6
1       1
2       8
3       1
4       0
       ..
763    10
764     2
765     5
766     1
767     1
Name: Pregnancies, Length: 768, dtype: int64

In [23]:
df.corr()

,Index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Outcome.1
Index,1.000000,0.241000,0.083791,-0.064371,-0.215358,0.390339,-0.364901,-0.264814,0.288982,0.142134,0.142134
Pregnancies,0.241000,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898,0.118031
Glucose,0.083791,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581,0.471787
BloodPressure,-0.064371,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068,0.082255
SkinThickness,-0.215358,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752,0.148601
Insulin,0.390339,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548,0.220964
BMI,-0.364901,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695,-0.076923
DiabetesPedigreeFunction,-0.264814,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844,0.087064
Age,0.288982,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356,0.260845
Outcome,0.142134,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000,1.000000
Outcome.1,0.142134,0.118031,0.471787,0.082255,0.148601,0.220964,-0.076923,0.087064,0.260845,1.000000,1.000000

In [24]:
df1 = pd.read_csv("/Users/macbook/Desktop/Machine Learning/pandas/dataset/diabetes.csv")

In [25]:
print(df1)

     Index  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      0.0            6      148             72             35        0  33.6
1      1.0            1       85             66             29        0  26.6
2      2.0            8      183             64              0        0  23.3
3      3.0            1       89             66             23       94  28.1
4      4.0            0      137             40             35      168  43.1
..     ...          ...      ...            ...            ...      ...   ...
763    NaN           10      101             76             48      180  32.9
764    NaN            2      122             70             27        0  36.8
765    NaN            5      121             72             23      112  26.2
766    NaN            1      126             60              0        0  30.1
767    NaN            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome  Outcome.1
0                       0.627   50        1        1.0
1                       0.351   31        0       -1.0
2                       0.672   32        1        1.0
3                       0.167   21        0       -1.0
4                       2.288   33        1        1.0
..                        ...  ...      ...        ...
763                     0.171   63        0        NaN
764                     0.340   27        0        NaN
765                     0.245   30        0        NaN
766                     0.349   47        1        NaN
767                     0.315   23        0        NaN

[768 rows x 11 columns]

In [26]:
df1.isnull().sum()

Index                       758
Pregnancies                   0
Glucose                       0
BloodPressure                 0
SkinThickness                 0
Insulin                       0
BMI                           0
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
Outcome.1                   741
dtype: int64

In [ ]:
df1.info()

In [27]:
new_df = df1.dropna()

In [28]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Index                     10 non-null     float64
 1   Pregnancies               10 non-null     int64
 2   Glucose                   10 non-null     int64
 3   BloodPressure             10 non-null     int64
 4   SkinThickness             10 non-null     int64
 5   Insulin                   10 non-null     int64
 6   BMI                       10 non-null     float64
 7   DiabetesPedigreeFunction  10 non-null     float64
 8   Age                       10 non-null     int64
 9   Outcome                   10 non-null     int64
 10  Outcome.1                 10 non-null     float64
dtypes: float64(4), int64(7)
memory usage: 960.0 bytes

In [29]:
df1.dropna(inplace = True)

In [30]:
x = df1["SkinThickness"].mean()
print(x)

19.9

In [32]:
md = df1["SkinThickness"].mode()[0]
print(md)

0